// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.opengis.nix.TareasRealizadasDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TareasRealizadasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TareasRealizadasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TareasRealizadasIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TareasRealizadasIntegrationTest: @Transactional;
    
    @Autowired
    private TareasRealizadasDataOnDemand TareasRealizadasIntegrationTest.dod;
    
    @Test
    public void TareasRealizadasIntegrationTest.testCountTareasRealizadases() {
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", dod.getRandomTareasRealizadas());
        long count = org.opengis.nix.TareasRealizadas.countTareasRealizadases();
        org.junit.Assert.assertTrue("Counter for 'TareasRealizadas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testFindTareasRealizadas() {
        org.opengis.nix.TareasRealizadas obj = dod.getRandomTareasRealizadas();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to provide an identifier", id);
        obj = org.opengis.nix.TareasRealizadas.findTareasRealizadas(id);
        org.junit.Assert.assertNotNull("Find method for 'TareasRealizadas' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TareasRealizadas' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testFindAllTareasRealizadases() {
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", dod.getRandomTareasRealizadas());
        long count = org.opengis.nix.TareasRealizadas.countTareasRealizadases();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TareasRealizadas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.opengis.nix.TareasRealizadas> result = org.opengis.nix.TareasRealizadas.findAllTareasRealizadases();
        org.junit.Assert.assertNotNull("Find all method for 'TareasRealizadas' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TareasRealizadas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testFindTareasRealizadasEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", dod.getRandomTareasRealizadas());
        long count = org.opengis.nix.TareasRealizadas.countTareasRealizadases();
        if (count > 20) count = 20;
        java.util.List<org.opengis.nix.TareasRealizadas> result = org.opengis.nix.TareasRealizadas.findTareasRealizadasEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TareasRealizadas' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TareasRealizadas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testFlush() {
        org.opengis.nix.TareasRealizadas obj = dod.getRandomTareasRealizadas();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to provide an identifier", id);
        obj = org.opengis.nix.TareasRealizadas.findTareasRealizadas(id);
        org.junit.Assert.assertNotNull("Find method for 'TareasRealizadas' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTareasRealizadas(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TareasRealizadas' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testMerge() {
        org.opengis.nix.TareasRealizadas obj = dod.getRandomTareasRealizadas();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to provide an identifier", id);
        obj = org.opengis.nix.TareasRealizadas.findTareasRealizadas(id);
        boolean modified =  dod.modifyTareasRealizadas(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.opengis.nix.TareasRealizadas merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TareasRealizadas' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", dod.getRandomTareasRealizadas());
        org.opengis.nix.TareasRealizadas obj = dod.getNewTransientTareasRealizadas(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TareasRealizadas' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TareasRealizadas' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TareasRealizadasIntegrationTest.testRemove() {
        org.opengis.nix.TareasRealizadas obj = dod.getRandomTareasRealizadas();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TareasRealizadas' failed to provide an identifier", id);
        obj = org.opengis.nix.TareasRealizadas.findTareasRealizadas(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TareasRealizadas' with identifier '" + id + "'", org.opengis.nix.TareasRealizadas.findTareasRealizadas(id));
    }
    
}
